---

- block:
  - name: add Spotify apt key
    ansible.builtin.apt_key:
      url: https://download.spotify.com/debian/pubkey_0D811D58.gpg
      state: present
    tags: ["spotify", "packages", "3rd-party-packages"]

  - name: configure Spotify repository
    ansible.builtin.apt_repository:
      repo: deb http://repository.spotify.com stable non-free
      state: present
      update_cache: yes
    tags: ["spotify", "packages", "3rd-party-packages"]

  - name: install Spotify
    ansible.builtin.apt:
      name: spotify-client
      state: latest
    tags: ["spotify", "packages", "3rd-party-packages"]
  become: yes
