"
" -- VIM configuration --
"

" Vundle setup
filetype off
set runtimepath+=~/.vim/bundle/Vundle.vim
call vundle#rc()

" Manage Vundle with Vundle
Plugin'VundleVim/Vundle.vim'

" Plugins
Plugin 'mileszs/ack.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-scripts/indentpython.vim'
Plugin 'edsono/vim-matchit'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'honza/vim-snippets'
Plugin 'godlygeek/tabular'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-ruby/vim-ruby'
Plugin 'rodjek/vim-puppet'
Plugin 'saltstack/salt-vim'
Plugin 'fatih/vim-go'
Plugin 'chase/vim-ansible-yaml'
Plugin 'plasticboy/vim-markdown'
Plugin 'vim-scripts/SyntaxRange'
Plugin 'vim-scripts/bats.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'vimwiki/vimwiki'
Plugin 'majutsushi/tagbar'

" Color schemas
Plugin 'brafales/vim-desert256'

set t_Co=256
set background=dark
colorscheme desert256

syntax on
filetype plugin on
filetype plugin indent on

set modeline
set backspace=2
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab
set showcmd
set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase
set autoindent
set title
set foldmethod=indent
set foldlevel=99
set laststatus=2

set encoding=utf8
set spelllang=pl

set backupdir=~/.vim/backups
set backup

au BufNewFile *.py   so ~/.vim/templates/tpl.py
au BufNewFile *.php  so ~/.vim/templates/tpl.php

au BufRead mutt-* setlocal spell spelllang=pl
au BufRead *.tex setlocal spell spelllang=pl
au BufRead *.twig   set ft=html
au BufRead *.txt set tw=78

au FileType go nmap <Leader>gd <Plug>(go-doc)
au FileType go nmap <Leader>gb <Plug>(go-doc-browser)
au FileType go nmap <Leader>i <Plug>(go-info)

au FileType puppet setlocal isk+=:
au FileType puppet nnoremap <c-]> :exe "tag " . substitute(expand("<cword>"), "^::", "", "")<CR>
au FileType puppet nnoremap <c-w><c-]> :tab split<CR>:exe "tag " . substitute(expand("<cword>"), "^::", "", "")<CR>

" jump to the last position when  reopening a file
if has("autocmd")
	au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

map <C-J> :bnext<CR>
map <C-K> :bprev<CR>
map <C-L> :tabn<CR>
map <C-H> :tabp<CR>

nmap <leader>t :NERDTreeToggle<CR>

nnoremap <Leader>rtw :%s/\s\+$//e<CR>

let NERDTreeKeepTreeInNewTab=1

let g:ackprg = 'ag --nogroup --nocolor --column'

let g:airline#extensions#tabline#show_buffers = 0
let g:airline#extensions#tabline#show_tabs = 0
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#hunks#enabled = 1
let g:airline_left_sep = ''
let g:airline_right_sep = ''

let g:ctrlp_extensions = ['tag']

let g:go_fmt_command = "goimports"

let g:ackprg="ack-grep -H --nocolor --nogroup --column"

" vimwiki
let g:vimwiki_list = [{'path': '~/priv/notes/', 'syntax': 'markdown', 'ext': '.md'}]

" tagbar
let g:tagbar_type_puppet = {
	\ 'ctagstype': 'puppet',
	\ 'kinds': [
		\'c:class',
		\'s:site',
		\'n:node',
		\'d:definition',
		\'r:resource',
		\'f:default'
	\]
\}
