---
- hosts: localhost
  connection: local
  roles:
    - role: base
    - role: firewall
    - role: vim
    - role: urxvt
    - role: firefox
    - role: evince
    - role: signal
    - role: spotify
    - role: oh-my-zsh
