---
- hosts: localhost
  connection: local
  vars:
    packages:
      - name: lightdm
      - name: xfce4
      - name: xfce4-goodies
      - name: xfce4-power-manager
      - name: eog
      - name: i3lock
      - name: xss-lock
      - name: awesome
      - name: awesome-extra
      - name: dzen2
      - name: rofi
      - name: surfraw
      - name: xfonts-terminus
      - name: ttf-mscorefonts-installer
      - name: network-manager
      - name: network-manager-gnome
      - name: network-manager-pptp
      - name: network-manager-pptp-gnome
      - name: network-manager-openvpn
      - name: network-manager-openvpn-gnome
      - name: rxvt-unicode-256color
      - name: gnome-keyring
      - name: seahorse
      - name: libsecret-tools
      - name: keepassx
      - name: pass
      - name: pavucontrol
      - name: goldendict
      - name: zsh
      - name: vim-nox
      - name: vim-gtk
      - name: screen
      - name: tmux
      - name: links
      - name: psmisc
      - name: dnsutils
      - name: less
      - name: lsof
      - name: mc
      - name: time
      - name: p7zip-full
      - name: zip
      - name: unzip
      - name: git
      - name: git-svn
      - name: git-annex
      - name: etckeeper
      - name: evince
      - name: zathura
      - name: subversion
      - name: tig
      - name: rsync
      - name: apg
      - name: bar
      - name: pv
      - name: grc
      - name: ntp
      - name: pm-utils
      - name: num-utils
      - name: htop
      - name: iotop
      - name: gnuplot
      - name: graphviz
      - name: qalc
      - name: tree
      - name: ncdu
      - name: lftp
      - name: xtightvncviewer
      - name: freerdp-x11
      - name: vlc
      - name: qnapi
      - name: unrar
      - name: tidy
      - name: sudo
      - name: telnet
      - name: imagemagick
      - name: rlwrap
      - name: httpie
      - name: curl
      - name: disper
      - name: arandr
      - name: suckless-tools
      - name: moreutils
      - name: python-keyring
      - name: strace
      - name: ltrace
      - name: stow
      - name: silversearcher-ag
      - name: calibre
      # networking tools
      - name: iftop
      - name: mtr
      - name: hping3
      - name: tcpdump
      - name: socat
      - name: netcat-traditional
      - name: ipcalc
      - name: sipcalc
      - name: wireshark
      - name: openvpn
      - name: nmap
      - name: rtorrent
      # webbrowsers
      - name: firefox
        release: experimental
      - name: chromium
      - name: flashplugin-nonfree
      # editing
      - name: texlive
      - name: texlive-bibtex-extra
      - name: texlive-fonts-extra
      - name: texlive-lang-polish
      - name: texlive-latex-extra
      - name: aspell-en
      - name: aspell-pl
      - name: myspell-pl
      - name: wpolish
      - name: pandoc
      - name: asciidoctor
      - name: libreoffice
      - name: pdftk
      - name: rubber
      # GPG
      - name: gnupg
      - name: signing-party # for caff
      # messaging & e-mail
      - name: mcabber
      - name: irssi
      - name: mutt
        release: unstable
      - name: khard
      - name: khal
      - name: urlview
      - name: notmuch
      - name: notmuch-mutt
      - name: offlineimap
      - name: msmtp
      - name: msmtp-mta
      # firewall
      - name: ferm
      # development tools
      - name: autoconf
      - name: automake
      - name: build-essential
      - name: flex
      - name: bison
      - name: linux-headers-amd64
      - name: ipython
      - name: java-package
      - name: nodejs
      - name: openjdk-8-jdk
      - name: python
      - name: python-dev
      - name: python-pip
      - name: python-sphinx
      - name: python3
      - name: python3-dev
      - name: ruby
      - name: ruby-dev
      - name: virtualenv
      - name: virtualenvwrapper
      - name: debhelper
      - name: devscripts
      - name: dh-make
      - name: pbuilder
      - name: quilt
      - name: git-buildpackage
      - name: cowbuilder
      - name: cmake
      - name: jq
      - name: shellcheck
      - name: meld
      - name: xmlstarlet
      - name: manpages-dev
      - name: exuberant-ctags
      - name: cscope
      # Yubikey
      - name: yubikey-personalization
      - name: yubikey-personalization-gui
      # wine
      - name: wine
      - name: winetricks
      # 3rd party
      - name: spotify-client
    alternatives:
      - name: x-terminal-emulator
        path: /usr/bin/urxvt
      - name: x-www-browser
        path: /usr/bin/firefox
      - name: editor
        path: /usr/bin/vim.nox
    default_applications:
      - { mimetype: application/pdf, application: evince.desktop }
      - { mimetype: x-scheme-handler/http, application: firefox.desktop }
      - { mimetype: x-scheme-handler/https, application: firefox.desktop }
    ferm_configuration: |
      domain (ip ip6) {
          table filter {
              chain INPUT {
                  policy DROP;
                  # connection tracking
                  mod state state INVALID DROP;
                  mod state state (ESTABLISHED RELATED) ACCEPT;
                  # allow local packet
                  interface lo ACCEPT;
                  # respond to ping
                  proto icmp ACCEPT;
              }
              chain OUTPUT {
                  policy ACCEPT;
                  # connection tracking
                  mod state state INVALID DROP;
                  mod state state (ESTABLISHED RELATED) ACCEPT;
              }
              chain FORWARD {
                  policy DROP;
                  # connection tracking
                  mod state state INVALID DROP;
                  mod state state (ESTABLISHED RELATED) ACCEPT;
              }
          }
      }
    apt_conf: |
      APT::Install-Recommends "0";
      APT::Install-Suggests "0";
    apt_keys:
      - id: BBEBDCB318AD50EC6865090613B00F1FD2C19886 # spotify
        keyserver: keyserver.ubuntu.com
    apt_repos:
      - "deb http://http.debian.net/debian experimental main non-free contrib"
      - "deb http://http.debian.net/debian unstable main non-free contrib"
      - "deb http://repository.spotify.com stable non-free"

  handlers:
    - name: restart ferm
      service:
        name: ferm
        state: restarted
      become: true

  tasks:
    - name: configure apt
      copy:
        dest: /etc/apt/apt.conf.d/02norecommends
        content: "{{ apt_conf }}"
      become: true
      tags: ['configuration::apt', 'apt::packages']

    - name: add additional apt keys
      apt_key:
        id: "{{ item.id }}"
        keyserver: "{{ item.keyserver }}"
        state: present
      with_items: "{{ apt_keys }}"
      become: true
      tags: ['configuration::apt', 'apt::packages']

    - name: add additional repositories
      apt_repository:
        repo: "{{ item }}"
        state: present
      with_items: "{{ apt_repos }}"
      become: true
      tags: ['configuration::apt', 'apt::packages']

    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: false
      become: true
      tags: ['apt::packages']

    - name: install basic packages
      apt:
        name: "{{ item.name }}"
        state: installed
        default_release: "{{ item.release | default() }}"
      with_items: "{{ packages }}"
      become: true
      tags: ['apt::packages']

    - name: update alternatives
      alternatives:
        name: "{{ item.name }}"
        path: "{{ item.path }}"
      with_items: "{{ alternatives }}"
      become: true
      tags: ['configuration::defaults']

    - name: create basic directories in user's home
      file:
        name: "{{ lookup('env', 'HOME') }}/{{ item }}"
        state: directory
      with_items:
        - bin/
        - .vim/backups # vim backups
        - .local/share/applications/ # stores mimeapps.list
      tags: ['configuration::defaults']

    - name: get a list default applications
      command: >
        /usr/bin/xdg-mime query default {{ item.mimetype }}
      with_items: "{{ default_applications }}"
      register: default_applications__list
      changed_when: false
      tags: ['configuration::defaults']

    - name: set default applications
      command: >
        /usr/bin/xdg-mime default {{ item.0.application }} {{ item.0.mimetype }}
      with_together:
        - "{{ default_applications }}"
        - "{{ default_applications__list.results }}"
      when: "item.0.application != item.1.stdout"
      tags: ['configuration::defaults']

    - name: install Vim Vundle plugin
      git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: "{{ lookup('env', 'HOME') }}/.vim/bundle/Vundle.vim"
      tags: ['configuration::vim']

    - name: install oh-my-zsh
      git:
        repo: git://github.com/robbyrussell/oh-my-zsh.git
        dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
      tags: ['configuration::zsh']

    - name: configure ferm
      copy:
        dest: /etc/ferm/ferm.conf
        content: "{{ ferm_configuration }}"
      notify: restart ferm
      become: true
      tags: ['configuration::firewall']

# vim: ts=2 sw=2 et
